<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="robot_height"   value="0.195"/>
  <xacro:property name="support_height"   value="1.6"/>
  <xacro:property name="support_mass"   value="2"/>
  <xacro:property name="a"   value="0.3"/> <!-- support length on x-->
  <xacro:property name="b"   value="0.15"/> <!-- support length on y-->
  <xacro:property name="c"   value="${support_height-robot_height}"/> <!-- support length on z-->

  <xacro:macro name="support" params="name parent">

	<link name="${name}_link">
       <inertial>
        <origin xyz="0 0 ${c/2}" rpy="0 0 0"/>
        <mass value="${support_mass}"/>
        <inertia ixx="${1/12*support_mass*(b*b+c*c)}" ixy="0.0" ixz="0.0"
                 iyy="${1/12*support_mass*(a*a+c*c)}" iyz="0.0"
                 izz="${1/12*support_mass*(a*a+b*b)}"/>
      </inertial>
		<visual>
		  <origin xyz="0 0 ${c/2}" rpy="0 0 0"/>
		  <geometry>      
		    <box size="0.3 0.15 ${c}"/>
		  </geometry>
		</visual>
      <collision>
  		  <origin xyz="0 0 ${c/2}" rpy="0 0 0"/>
		  <geometry>      
		    <box size="0.3 0.15 ${c}"/>
		  </geometry>
      </collision>
	  </link>

    <joint name="support_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <origin xyz="0 0 ${robot_height}" rpy="0 0 0"/>
    </joint>


    <gazebo reference="${name}_link">
      <material>Gazebo/Red</material>
    </gazebo>
  </xacro:macro>
</robot>
